Add support for the armv6-vfp processor target
This is a squashed commit of the following from CM's froyo tree:

commit 05e32f9502d357d4cdc419d589ab4252f153da1f
Author: Ricardo Cerqueira <cyanogenmod@cerqueira.org>
Date:   Tue Nov 9 01:27:18 2010 +0000

    dalvik: Finish armv6-vfp support

commit 39d5cf768028ecad60a2c8f5252dc8b79c96bcc8
Author: Gary King <gking@nvidia.com>
Date:   Wed Nov 18 14:07:21 2009 -0800

    dalvik: add support for armv6-vfp processor target

    adds specialized support for ARMv6 w/ VFP to the Dalvik interpreter

and, in addition: Do some minor updates necessary for gingerbread,
mostly deleting unused variables to fix these:

cc1: warnings being treated as errors
dalvik/vm/mterp/out/InterpC-armv6-vfp.c: In function 'dvmMterpDumpArmRegs':
dalvik/vm/mterp/out/InterpC-armv6-vfp.c:1232: error: unused variable 'glue'
dalvik/vm/mterp/out/InterpC-armv6-vfp.c:1235: error: unused variable 'method
dalvik/vm/mterp/out/InterpC-armv6-vfp.c:1227: error: unused variable 'dvmAsm

Change-Id: I929bb74b0f72ffd2c7ef498b5b76fe800b2c7c66

Conflicts:

	vm/compiler/template/rebuild.sh
	vm/mterp/rebuild.sh